# Generated by Django 2.1.1 on 2020-12-16 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20201216_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 19, 20, 63672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 19, 20, 63950, tzinfo=utc)),
        ),
    ]
