# Generated by Django 2.1.1 on 2020-12-16 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20201216_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidder',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 21, 13, 35708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 21, 13, 36102, tzinfo=utc)),
        ),
    ]
