# Generated by Django 2.1.1 on 2020-12-16 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20201216_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidder',
            old_name='update_at',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 23, 47, 302642, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 9, 23, 47, 302912, tzinfo=utc)),
        ),
    ]
