# Generated by Django 2.1.1 on 2020-12-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_auto_20201216_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidder',
            name='auctioneer',
            field=models.UUIDField(),
        ),
    ]
